### ISSUE TITLE
minor issue

### ISSUE THREAD

**Issue by romanegloo** [terrier-org/terrier-core#1]
I guess 4.2 core binary version is not in gzip format.
I was able to untar without -z option though.

**Comment by cmacdonald** [comment]
I just checked, its definitely in gzip format:
```
$file terrier-core-4.2-bin.tar.gz 
terrier-core-4.2-bin.tar.gz: gzip compressed data
```
Some browsers decompress automatically (e.g. Safari). I suspect that is what has happened here.

**Comment by romanegloo** [comment]
Indeed the file I downloaded is decompressed.
--($:~/Downloads)-- file terrier-core-4.2-bin.tar.gz
terrier-core-4.2-bin.tar.gz: POSIX tar archive

This should not be decompressed automatically because the file is named tar.gz

I found a similar issue from here: http://superuser.com/questions/940605/chromium-prevent-unpacking-tar-gz
You may need to check the web server configs as described in one of the answers.

**Comment by cmacdonald** [comment]
Thanks for the useful pointer. We'll see if the webserver config can be revised to address this point.
