### ISSUE TITLE
Empty checks required for feedback documents in query expansion-based retrieval

### ISSUE THREAD

**Issue by wangxieric** [terrier-org/terrier-core#124]
Problem:
ArrayIndexOutOfBounds error when using the following model
firstpass_dph_qiqe = ~(pt.BatchRetrieve(newindex, wmodel="DPH") >> Bo1QueryExpansion(queryindex) >> firstpass_dph) 

Problem Trace: 
['java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0', 'org.terrier.querying.DFRBagExpansionTerms.assignWeights(DFRBagExpansionTerms.java:311)', 'org.terrier.querying.DFRBagExpansionTerms.getExpandedTerms(DFRBagExpansionTerms.java:161)', 'org.terrier.querying.DFRBagExpansionTerms.getExpandedTerms(DFRBagExpansionTerms.java:156)', 'org.terrier.querying.QueryExpansion.expandQuery(QueryExpansion.java:207)']

Possible reason:  retrieved documents with the DPH model and the normal index have no previous queries in the queries index.

Possible solution: we need an "if (len == 0) return" at https://github.com/terrier-org/terrier-core/blob/5.x/modules/core/src/main/java/org/terrier/querying/DFRBagExpansionTerms.java#L280
Extra testings are also required.

**Comment by cmacdonald** [comment]
Fixed.
