### ISSUE TITLE
issue query got IllegalStateException

### ISSUE THREAD

**Issue by ArvinZhuang** [terrier-org/terrier-core#129]
Hi, 
when I try to interactive and batchretrieve to issue queries, I always got IllegalStateException: no result found.
I'm very sure that I correctly indexed the collection and set the . properties file.
Any other possible that can raise this error? 
Thanks.

**Comment by cmacdonald** [comment]
Hi,

can you show more precisely the input and output of the system?

Craig

**Comment by ArvinZhuang** [comment]
![image](https://user-images.githubusercontent.com/46237844/89643592-720afb00-d8f9-11ea-9597-59f9e342bc99.png)

here is my terrier.properties file:

> xml.doctag=PubmedArticle
xml.idtag=PMID
xml.terms=ArticleTitle,AbstractText,Keyword
trec.collection.class=SimpleXMLCollection
querying.postfilters=decorate:org.terrier.querying.SimpleDecorate
querying.processes=terrierql:TerrierQLParser,parsecontrols:TerrierQLToControls,parseql:TerrierQLToMatchingQueryTerms,matchopql:MatchingOpQLParser,applypipeline:ApplyTermPipeline,localmatching:LocalManager$ApplyLocalMatching,filters:LocalManager$PostFilterProcess
querying.default.controls=terrierql:on,parsecontrols:on,parseql:on,applypipeline:on,localmatching:on,filters:on,decorate:on
trec.topics=QUERIES.txt
trec.topics.parser=SingleLineTRECQuery
trec.model=BM25

Seems it only did the previous 3 processes and ignored the rests?

**Comment by cmacdonald** [comment]
Pretty weird. 

Can you compare your properties with:
https://github.com/terrier-org/terrier-core/blob/5.x/modules/core/src/main/resources/terrier.default.properties

ALSO, can you set logging to DEBUG (change INFO to DEBUG in etc/logback.xml)

**Comment by ArvinZhuang** [comment]
Hi Craig

I just tried the exact same setting on another machine and everything works well. 
my guess is the stupid editor automatically changed something after I opened the properties file.

Anyway, thank you for your help!

**Comment by cmacdonald** [comment]
Good to hear. Btw, have you seen Pyterrier?

**Comment by ArvinZhuang** [comment]
No, but you recommend to try out?

**Comment by cmacdonald** [comment]
Yes, do give a look. It uses Terrier underneath, enables more flexible experimentation. Myself, I use Pyterrier now rather than "terrier batchretrieve"

See https://github.com/terrier-org/pyterrier

**Comment by ArvinZhuang** [comment]
That's nice! thank you
