### ISSUE TITLE
Non-English batchretrieve throws Exception.

### ISSUE THREAD

**Issue by harshhp8** [terrier-org/terrier-core#140]
I have indexed non-English language but not able to batch retrieve it. It shows exception like "Topic files were specified, but non could be parsed correctly to obtain any topics. Check you have the correct topic files specified, and that tags are correct.
".Am I missing something in the terrier-properties file in version 5.3.
![Screenshot from 2020-11-27 08-49-02](https://user-images.githubusercontent.com/8132743/100407066-6cdee100-308d-11eb-9d84-abe51b9905e1.png)

**Comment by cmacdonald** [comment]
can you show example of your topics file?

**Comment by harshhp8** [comment]
Hello,This is my topic file in non-english.(Marathi Language)
<topic>

<top lang='mr'>
<num>126</num>
<title>स्वाईन फ्लू लस</title>
<desc>स्वाईन फ्लूच्या प्रतिबंधासाठी भारतात तयार करण्यात आलेली स्वेदशी लस</desc>
<narr>प्रासंगिक लेखांत भारतात तयार करण्यात येणार्‍या स्वेदशी स्वाईन फ्लू लसी, मानव आणि प्राणि यांवर वापरण्यात येणार्‍या लसी, लसीची कमतरता/अनुपलब्धता दूर करण्यासाठी केलेली व्यवस्था, आणि जीव वाचवण्यात लसींची भूमिका या संबंधी माहिती असली पाहिजे.</narr>
</top>

<top lang='mr'>
<num>127</num>
<title>दुर्मिळ अंतरिक्षीय घटना</title>
<desc>दुर्मिळ सौरग्रहण, चंद्रग्रहण, उल्कापात, पृथ्वी संबंधी तार्‍यांच्या जागेमध्ये होणारे बदल याविषयी माहिती</desc>
<narr>प्रासंगिक लेखांत या घटनां संबंधी लोकांच्या उलट प्रतिक्रिया असल्या पाहिजेत. या घटना दुर्मिळ का आहेत त्यांची कारणे, आणि ज्योतिषतज्ञ व वैज्ञानिक ह्यांच्यामधील मतभेद हे प्रासंगिक आहेत. अंतराळयान, पृथ्वीच्या बाहेरील जीवनाचे अस्तित्व हे अप्रासंगिक आहेत आणि अंतराळ संशोधनावरील माहिती ही अप्रासंगिक आहे.  दु्र्मिळ घटनांचे केलेले वर्णन एवढे महत्त्वाचे नाही.</narr>
</top>

<top lang='mr'>
<num>128</num>
<title>गोध्रा ट्रेन आक्रमण</title>
<desc>गोध्रामध्ये साबरमती जलद ट्रेनमध्ये झालेल्या गोळीबारातील मृतांची किंवा जखमींची संख्या</desc>
<narr>प्रासंगिक लेखांत गोध्रामध्ये साबरमती जलद ट्रेनमध्ये झालेल्या आक्रमणात मृतांची किंवा जखमींची संख्या, आणि दिलेल्या अहवालामधील आकड्यांशी संबंधित असलेले मतभेद याविषयी माहिती असली पाहिजे.</narr>
</top>
</topic>

**Comment by harshhp8** [comment]
This is sample of my topic.`<topic>

<top lang='mr'>
<num>126</num>
<title>स्वाईन फ्लू लस</title>
<desc>स्वाईन फ्लूच्या प्रतिबंधासाठी भारतात तयार करण्यात आलेली स्वेदशी लस</desc>
<narr>प्रासंगिक लेखांत भारतात तयार करण्यात येणार्‍या स्वेदशी स्वाईन फ्लू लसी, मानव आणि प्राणि यांवर वापरण्यात येणार्‍या लसी, लसीची कमतरता/अनुपलब्धता दूर करण्यासाठी केलेली व्यवस्था, आणि जीव वाचवण्यात लसींची भूमिका या संबंधी माहिती असली पाहिजे.</narr>
</top>

<top lang='mr'>
<num>127</num>
<title>दुर्मिळ अंतरिक्षीय घटना</title>
<desc>दुर्मिळ सौरग्रहण, चंद्रग्रहण, उल्कापात, पृथ्वी संबंधी तार्‍यांच्या जागेमध्ये होणारे बदल याविषयी माहिती</desc>
<narr>प्रासंगिक लेखांत या घटनां संबंधी लोकांच्या उलट प्रतिक्रिया असल्या पाहिजेत. या घटना दुर्मिळ का आहेत त्यांची कारणे, आणि ज्योतिषतज्ञ व वैज्ञानिक ह्यांच्यामधील मतभेद हे प्रासंगिक आहेत. अंतराळयान, पृथ्वीच्या बाहेरील जीवनाचे अस्तित्व हे अप्रासंगिक आहेत आणि अंतराळ संशोधनावरील माहिती ही अप्रासंगिक आहे.  दु्र्मिळ घटनांचे केलेले वर्णन एवढे महत्त्वाचे नाही.</narr>
</top>

<top lang='mr'>
<num>128</num>
<title>गोध्रा ट्रेन आक्रमण</title>
<desc>गोध्रामध्ये साबरमती जलद ट्रेनमध्ये झालेल्या गोळीबारातील मृतांची किंवा जखमींची संख्या</desc>
<narr>प्रासंगिक लेखांत गोध्रामध्ये साबरमती जलद ट्रेनमध्ये झालेल्या आक्रमणात मृतांची किंवा जखमींची संख्या, आणि दिलेल्या अहवालामधील आकड्यांशी संबंधित असलेले मतभेद याविषयी माहिती असली पाहिजे.</narr>
</top>
</topic>


`
![Screenshot from 2020-11-27 18-56-39](https://user-images.githubusercontent.com/8132743/100454118-4b5c1480-30e2-11eb-8bfe-3422fcd828c9.png)

**Comment by cmacdonald** [comment]
based on the example you send/showed, the error message seems correct - there is no id tag.

Look at this example from https://github.com/terrier-org/terrier-core/blob/5.x/share/vaswani_npl/query-text.trec:
```
<top>
<num>1</num><title>
MEASUREMENT OF DIELECTRIC CONSTANT OF LIQUIDS BY THE USE OF MICROWAVE TECHNIQUES
</title>
</top>
```

Craig

**Comment by cmacdonald** [comment]
Hi @harshhp8 

[revised comment]

can you take the ` lang=""` attribute out of the top tag and see if it works

I think you will also need to change the tokeniser.
`-Dtokeniser=UTFTokeniser` should work

(at least the latter, if not the former as well)

**Comment by harshhp8** [comment]
We have setup id tag in terrier.property file like this

#query tags specification
TrecQueryTags.doctag=TOPICS
TrecQueryTags.idtag=NUM
TrecQueryTags.process=TOPICS,NUM,TITLE
TrecQueryTags.skip=DESC,NARR

**Comment by harshhp8** [comment]
> Hi @harshhp8
> 
> [revised comment]
> 
> can you take the ` lang=""` attribute out of the top tag and see if it works
> 
> I think you will also need to change the tokeniser.
> `-Dtokeniser=UTFTokeniser` should work
> 
> (at least the latter, if not the former as well)

sure let me.

**Comment by cmacdonald** [comment]
Can you paste your terrier.properties file?

**Comment by harshhp8** [comment]
terrier.property file.
#default controls for manager
querying.processes=terrierql:TerrierQLParser,parsecontrols:TerrierQLToControls,parseql:TerrierQLToMatchingQueryTerms,matchopql:MatchingOpQLParser,applypipeline:ApplyTermPipeline,localmatching:LocalManager$ApplyLocalMatching,qe:QueryExpansion,labels:org.terrier.learning.LabelDecorator,filters:LocalManager$PostFilterProcess
#default controls for the web-based interface. SimpleDecorate
#is the simplest metadata decorator. For more control, see Decorate.
querying.postfilters=decorate:SimpleDecorate,site:SiteFilter,scope:Scope

#default and allowed controls
querying.default.controls=wmodel:DPH,parsecontrols:on,parseql:on,applypipeline:on,terrierql:on,localmatching:on,filters:on,decorate:on
querying.allowed.controls=scope,qe,qemodel,start,end,site,scope

#document tags specification
#for processing the contents of
#the documents, ignoring DOCHDR
TrecDocTags.doctag=DOC
TrecDocTags.idtag=DOCNO
TrecDocTags.skip=DOCHDR
#set to true if the tags can be of various case
TrecDocTags.casesensitive=false
#starting from Terrier 5.3, we assume that documents are in UTF-8
#trec.encoding=UTF-8
#trec.encoding=ISO 8859-16

#query tags specification
TrecQueryTags.doctag=TOPICS
TrecQueryTags.idtag=NUM
TrecQueryTags.process=TOPICS,NUM,TITLE
TrecQueryTags.skip=DESC,NARR
#trec.encoding=UTF-8

#the processing stages a term goes through
#termpipelines=Stopwords,PorterStemmer
#termpipelines=
trec.collection.class=TRECCollection
string.use_utf=false
indexer.meta.forward.keylens=80
#tokeniser=IdentityTokeniser
#tokeniser=UTFTokeniser

**Comment by cmacdonald** [comment]
`string.use_utf=false` looks OLD, and should be removed
you will need a tokeniser that matches your indexing setup and appropriate for the language you are working in. I suspect latter is the problem

**Comment by harshhp8** [comment]
> `string.use_utf=false` looks OLD, and should be removed
> you will need a tokeniser that matches your indexing setup and appropriate for the language you are working in. I suspect latter is the problem

I had to try all the options as #tokeniser=UTFTokeniser was also not working.i will give you the updated file now. Indexing works just fine.

**Comment by cmacdonald** [comment]
you should use the `indexutil` command to print the lexicon, to see what terms are indexed.

**Comment by harshhp8** [comment]
> indexutil

Using Indexutil, it indexes non-English words just fine. but at the time of batch retrieval, it shows the same error.

**Comment by harshhp8** [comment]
> you should use the `indexutil` command to print the lexicon, to see what terms are indexed.

I have put only one topic and I think I got something. Let me share with you. Removing " " in topic worked but with another error.
This is terrier-property file.
#default controls for manager
querying.processes=terrierql:TerrierQLParser,parsecontrols:TerrierQLToControls,parseql:TerrierQLToMatchingQueryTerms,matchopql:MatchingOpQLParser,applypipeline:ApplyTermPipeline,localmatching:LocalManager$ApplyLocalMatching,qe:QueryExpansion,labels:org.terrier.learning.LabelDecorator,filters:LocalManager$PostFilterProcess
#default controls for the web-based interface. SimpleDecorate
#is the simplest metadata decorator. For more control, see Decorate.
querying.postfilters=decorate:SimpleDecorate,site:SiteFilter,scope:Scope

#default and allowed controls
querying.default.controls=wmodel:DPH,parsecontrols:on,parseql:on,applypipeline:on,terrierql:on,localmatching:on,filters:on,decorate:on
querying.allowed.controls=scope,qe,qemodel,start,end,site,scope

#document tags specification
#for processing the contents of
#the documents, ignoring DOCHDR
TrecDocTags.doctag=DOC
TrecDocTags.idtag=DOCNO
TrecDocTags.skip=DOCHDR
#set to true if the tags can be of various case
TrecDocTags.casesensitive=false
#starting from Terrier 5.3, we assume that documents are in UTF-8
trec.encoding=UTF-8
#trec.encoding=ISO 8859-16

#query tags specification
TrecQueryTags.doctag=TOPIC
TrecQueryTags.idtag=NUM
TrecQueryTags.process=TOPICS,NUM,TITLE
TrecQueryTags.skip=DESC,NARR
#trec.encoding=UTF-8

#the processing stages a term goes through
#termpipelines=Stopwords,PorterStemmer
#termpipelines=
#trec.collection.class=TRECCollection
#string.use_utf=false
indexer.meta.forward.keylens=80
#tokeniser=IdentityTokeniser
tokeniser=UTFTokeniser
 

And output.
![Screenshot from 2020-11-27 19-14-27](https://user-images.githubusercontent.com/8132743/100455483-c7eff280-30e4-11eb-97a9-b7cba94a6490.png)
[topic.txt](https://github.com/terrier-org/terrier-core/files/5608087/topic.txt)

**Comment by cmacdonald** [comment]
Hi, sorry for the latency. I think the current Terrier github sourcecode should have fixed this. Let me know if it hasnt.
