### ISSUE TITLE
Missing Wiki and other questions

### ISSUE THREAD

**Issue by nwrbs** [terrier-org/terrier-core#149]
Hi, 
I'm new to Terrier and I'm trying to come up to speed.  However, I finding some missing pieces.
Wiki:  The documentation references a wiki, but I'm unable to find it and the corresponding documentation:
http://ir.dcs.gla.ac.uk/wiki/Terrier
http://ir.dcs.gla.ac.uk/wiki/Terrier/Disks1&2
http://ir.dcs.gla.ac.uk/wiki/Terrier/IndexStructures
http://ir.dcs.gla.ac.uk/wiki/Terrier/CollectionOfFiles

Some of the older documentation references (on the HTML pages) a forum, http://terrier.org/forum, which appears to no longer exist.  Does it exist?  if so where?  If not, what is the best place to ask questions?  even simple ones.  It's probably not github's issue tracker?

Thanks for the help!
Brad

**Comment by cmacdonald** [comment]
Hi Brad,

Here is fine. Most of us are using PyTerrier now as an easier way to use Terrier. See https://pyterrier.readthedocs.io/en/latest/

Craig

**Comment by nwrbs** [comment]
Thanks for the information.  Unfortunately, I'll be using Terrier via Java mainly because I looking at the aspects of extending the indexing and retrieval process via some customizations to fit my particular needs.

Thanks
Brad

**Comment by cmacdonald** [comment]
sure, but you might find it easier to run from Python. Anyway, fire questions here if you have any.
