### ISSUE TITLE
Unable to fine defintions for ParseException and TokenMgrError

### ISSUE THREAD

**Issue by nwrbs** [terrier-org/terrier-core#150]
Trying to build the project in Intellij but I'm getting errors on 
../terrier-core/modules/core/src/main/java/org/terrier/querying/MatchingOpQLParser.java

java: cannot find symbol:   class ParseExceptionParseException
java: cannot find symbol:   class TokenMgrError

34 | import org.terrier.matching.matchops.ParseException;
35 | import org.terrier.matching.matchops.TokenMgrError;

I grepped the terrier-core directory and could not find any definitions for either:
Did I miss something?

**Comment by cmacdonald** [comment]
Use Maven to build. These are created by Maven plugins.
