### ISSUE TITLE
What about this Documentation (4.2) I want to try an example like this in version 5.4 but i lack of knowledge in Terrier new Releases and Techniques

### ISSUE THREAD

**Issue by Deca99** [terrier-org/terrier-core#158]
import java.io.File;
import java.io.FileReader;
import java.util.HashMap;
import org.terrier.indexing.Collection;
import org.terrier.indexing.SimpleFileCollection;
import org.terrier.matching.ResultSet;
import org.terrier.querying.Manager;
import org.terrier.querying.SearchRequest;
import org.terrier.structures.indexing.classical.BasicIndexer;

public class IndexingAndRetrievalExample {

    public static void main(String[] args) throws Exception {

        // Directory containing files to index
        String aDirectoryToIndex = "/my/directory/containing/files/";

        // Configure Terrier
        ApplicationSetup.setProperty("indexer.meta.forward.keys", "filename");
        ApplicationSetup.setProperty("indexer.meta.forward.keylens", "200");

        Indexer indexer = new BasicIndexer("/path/to/my/index", "data");
        Collection coll = new SimpleFileCollection(Arrays.asList(aDirectoryToIndex), true);
        indexer.index(new Collection[]{coll});
        indexer.close();

        Index index = Index.createIndex("/path/to/my/index", "data");

    // Enable the decorate enhancement
    ApplicationSetup.setProperty("querying.postfilters.order", "org.terrier.querying.SimpleDecorate");
        ApplicationSetup.setProperty("querying.postfilters.controls", "decorate:org.terrier.querying.SimpleDecorate");

    // Create a new manager run queries
        Manager queryingManager = new Manager(index);

    // Create a search request
        SearchRequest srq = queryingManager.newSearchRequestFromQuery("search for document");

    // Specify the model to use when searching
        srq.addMatchingModel("Matching","BM25");

    // Turn on decoration for this search request
        srq.setControl("decorate", "on");

    // Run the search
        queryingManager.runSearchRequest(srq);

    // Get the result set
        ResultSet results = srq.getResultSet();

    // Print the results
        System.out.println(results.getExactResultSize()+" documents were scored");
        System.out.println("The top "+results.getResultSize()+" of those documents were returned");
        System.out.println("Document Ranking");
        for (int i =0; i< results.getResultSize(); i++) {
            int docid = results.getDocids()[i];
            double score = results.getScores()[i];
            System.out.println("   Rank "+i+": "+docid+" "+results.getMetaItem("filename", docid)+" "+score);
        }
  }
}

**Comment by cmacdonald** [comment]
Most of this code should still work in Terrier 5.4. Did you try the code?

However, we recommend using Terrier via [PyTerrier](https://github.com/terrier-org/pyterrier) which makes all of this much easier.

**Comment by Deca99** [comment]
I have to do a Java Project in University. 

It gives me errors in some classes.
![image](https://user-images.githubusercontent.com/60140163/115881689-ad803200-a454-11eb-8f10-dae9d8833b30.png)


and also some things are deprecated
![image](https://user-images.githubusercontent.com/60140163/115881774-c557b600-a454-11eb-9354-831edcab2895.png)


aaand also some things cant happen anymore 
![image](https://user-images.githubusercontent.com/60140163/115881853-d7d1ef80-a454-11eb-9484-4408e344ba3c.png)


Can i find somewhere kind of Documentation for new methods? 
I just need to index and retrieve a simple (and small) trec file to get things going for now and understand how things work.

**Comment by cmacdonald** [comment]
Deprecation warnings are fine - the APIs should still work.
All the main documentation is on Github now - see this example, which I believe is up-to-date:
https://github.com/terrier-org/terrier-core/blob/5.x/doc/quickstart-integratedsearchdisk.md

E.g. using a ManagerFactory to get the Manager.

Craig

**Comment by Deca99** [comment]
Thank you for your time! I appreciate it!
