### ISSUE TITLE
Integrating terrier with another app

### ISSUE THREAD

**Issue by miraymak** [terrier-org/terrier-core#159]
Hi,
I have been trying to integrate Terrier with an app I am working on. I tried to follow the quick start guide provided. However, I cannot seem to make it work and I am not sure if I am missing any steps.

I have attached the App.java and pom.xml for my application. 
the .m2/repository has the terrier dependencies downloaded .
but when I run the App using: java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App

i get the following error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/terrier/querying/IndexRef
        at com.mycompany.app.App.main(App.java:30)
Caused by: java.lang.ClassNotFoundException: org.terrier.querying.IndexRef
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more
[App.zip](https://github.com/terrier-org/terrier-core/files/6422958/App.zip)

I would appreciate the help.

**Comment by cmacdonald** [comment]
Hi @miraymak

I think you need more dependencies - the terrier-retrieval-api? (though I thought Maven would import them)

NB: I know you are in Java rather than in Python, but most of our emphasis these days is in using [PyTerrier](https://github.com/terrier-org/pyterrier), which handles all the Jar importing stuff automatically.

Craig

**Comment by cmacdonald** [comment]
Any news?

**Comment by miraymak** [comment]
Hi,

Unfortunately, i couldn't fix the errors in java project.  So I used the pyterrier, python package. It was a bit challenging since i am using windows. 

Please note that in the pyterrier, the FileIndexer class was giving an error related to "meta" properties. Some pieces of codes in the index.py are missing and not as indicated in the documentation, some of the init method's params for instance and the _TaggedDocumentSetup method were missing. 

Thank you for the follow-up

**Comment by cmacdonald** [comment]
Thanks. We will shortly release a PyTerrier version that installs and works on Windows. 

If you can post issues for FileIndexer, I can ensure they are noted for being addressed in due course. 

Closing this issue.
