### ISSUE TITLE
[beginner] Can I maintain multiple indices with different properties? 

### ISSUE THREAD

**Issue by marcosfpr** [terrier-org/terrier-core#168]
Studying the documentation of Terrier, I realized that all the configuration of the indexes is done through the static class `ApplicationSetup`. That's what happens, right?

Is there a way to create different configurations to maintain multiple indexes? e.g. for a multi-user system, in which a server needs to maintain and configure indexes for different collections and users.

I didn't find an answer to that. I'm sorry if this is a beginner question.

**Comment by cmacdonald** [comment]
Hi Marcos,

Thanks for an excellent question. Yes, they are global variables, which we've been working slowly to eliminate over the years.

At present, a lot of retrieval can be configured without changing properties. We know this is tricky, which as you may know, is why a lot of our more recent efforts have centred around [PyTerrier](https://github.com/terrier-org/pyterrier). PyTerrier exposes as much configuration as possible through a more developer/researcher-friendly API.

For indexing, a bit more of the configuration is through properties. Notable things that can be configured in Java without properties include the source being indexed (c.f. collection.spec) and destination location. You mention "maintain[ing] multiple indices". If you could detail the configurations that you expect will need to differ between indices, we can see what is possible or not. For indexing, PyTerrier sets all the relevant properties before indexing, to prevent contamination. 

Craig

**Comment by marcosfpr** [comment]
Hi Craig,

Thank you for the quickly and really useful answer. Well, I'm starting the development of a tool called "[MatchUp](http://matchup.ufop.br/login)", which is an experimental/educational information retrieval tool. The main goal of MatchUp is to provide a friendly interface to users create and manage your collections, perform queries and analyze the models' throughput. 

Thus, I was thinking to use terrier as the MatchUp's search engine, since terrier it's an extremely interesting IR library for that purposes. However, I need to provide to multiple users the capability of configure how it's collection will be indexed and what models they will test. So, with these static configuration of terrier I imagine that this may not work. 

I don't know if you understand the problem. If you want I can try to detail a little more about it. Thank you for the support!

Marcos

**Comment by cmacdonald** [comment]
This may not suite your targeted development environment, but I would recommend PyTerrier. It allows much more interesting retrieval pipelines to be constructed, in a programatic fashion.

**Comment by marcosfpr** [comment]
Ok, I'll look at PyTerrier!
