### ISSUE TITLE
No per-query output with `batchevaluate -p`

### ISSUE THREAD

**Issue by umazalakain** [terrier-org/terrier-core#18]
No per-query output is generated when the -p switch is used: the output in var/results/*.eval is exactly the same as when the switch is not used.

**Comment by cmacdonald** [comment]
Oh my word. Good find, and thanks for your efforts. This was a one-line fix in Terrier, so I have fixed this (see https://github.com/terrier-org/terrier-core/commit/34b77b9d13813364b23ba122916ac70042b7dbbe) and replaced the 5.1 tar files on the Terrier website.
