### ISSUE TITLE
Terrier Forum Down

### ISSUE THREAD

**Issue by nadeeer** [terrier-org/terrier-core#183]
Hello there,
I'm not able to access the terrier forum at http://terrier.org/forum/ and I get the 404 error code: "Not Found The requested URL /forum/ was not found on this server."

**Comment by cmacdonald** [comment]
Please use this issue tracker instead.

**Comment by nadeeer** [comment]
You mean to use the issue tracker instead of the forum?
I really liked the forum because I can find many answers to the questions I have from past posts over the years.

**Comment by cmacdonald** [comment]
We lost the machine that hosted it about 6 months ago; sorry. I'll try to find it we have the database.

All our focus is now on use of Terrier via the PyTerrier layer.

**Comment by nadeeer** [comment]
Sorry to hear that!
I'll use the issue tracker to ask my question
