### ISSUE TITLE
significant figures in average precision values

### ISSUE THREAD

**Issue by nadeeer** [terrier-org/terrier-core#184]
How can I increase the significant figures in average precision values returned by the evaluation script. For example, for one of the queries I have the average precision to be 0.0053. I'd like it to be something like 0.00528765.

Thank you!

**Comment by cmacdonald** [comment]
Hi nadeer,

I think most of Terrier's results come from trec_eval, which only reports to 4dps IIRC. 

I think PyTerrier gives more flexibility in this respect.

Craig
