### ISSUE TITLE
Set the number of retrieved results

### ISSUE THREAD

**Issue by kite1988** [terrier-org/terrier-core#190]
Hi,

I would like to output all retrieved results (instead of 1000 top results by default) in Terrier. Following the [instruction](https://github.com/terrier-org/terrier-core/blob/6ecf53301f9dadd637edf9e417c108ff658a627d/doc/configure_retrieval.md#other-configurables), I add the following line in the terrier.properties. 

> matching.retrieved_set_size=0

However, this command seems not working, as the output still only contains 1000 results.   I also tried to increase the number from "0" to "8000000",  but the results are the same. I am using Terrier 5.4.  May I know the correct way of setting this property?

Thanks!

**Comment by cmacdonald** [comment]
Looks like the correct property - see
https://github.com/terrier-org/terrier-core/blob/5.x/modules/core/src/main/java/org/terrier/matching/BaseMatching.java#L190

Have you tried PyTerrier? - it makes changing these configurations a bit easier.

**Comment by kite1988** [comment]
I tried to add the following in the terrier.properties. Now Terrier can output all results.

> matching.retrieved_set_size=0
> trec.output.format.length=0

**Comment by cmacdonald** [comment]
Well remembered. Could you make a PR to the documentation?
