### ISSUE TITLE
ARM is not supported

### ISSUE THREAD

**Issue by Nockda** [terrier-org/terrier-core#217]
Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
/var/folders/dd/g4twb_l567bf15519ypmvd600000gn/T/ipykernel_61270/622872623.py in <module>
      1 import pyterrier as pt
      2 if not pt.started():
----> 3   pt.init()
      4 
      5 import pandas as pd

~/opt/anaconda3/lib/python3.9/site-packages/pyterrier/__init__.py in init(version, mem, packages, jvm_opts, redirect_io, logging, home_dir, boot_packages, tqdm, no_download, helper_version)
    126     if mem is not None:
    127         jnius_config.add_options('-Xmx' + str(mem) + 'm')
--> 128     from jnius import autoclass, cast
    129 
    130     # we only accept Java version 11 and newer; so anything starting 1. or 9. is too old

~/opt/anaconda3/lib/python3.9/site-packages/jnius/__init__.py in <module>
     43 else:
     44     from .jnius import *  # noqa
---> 45     from .reflect import *  # noqa
     46 
     47 from six import with_metaclass

~/opt/anaconda3/lib/python3.9/site-packages/jnius/reflect.py in <module>
     18 
...
jnius/jnius_jvm_dlopen.pxi in jnius.get_platform_jnienv()

jnius/jnius_jvm_dlopen.pxi in jnius.create_jnienv()

SystemError: Error calling dlopen(b'/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/lib/jli/libjli.dylib'): b"dlopen(/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/lib/jli/libjli.dylib, 0x000A): tried: '/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/lib/jli/libjli.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))"

**Comment by cmacdonald** [comment]
Probably you have an M1 Mac, and there is no compatible jnius library?

Or your Python (x86_64) build mismatches your Java build (arm64)?

**Comment by cmacdonald** [comment]
What is `platform.machine`() in Python, and `java -version` from the commandline?

Further, can you run the following using `jshell` from the command line:
```
jshell> import java.lang.System
jshell> System.getProperty("os.arch")
```
and paste the output?

**Comment by Nockda** [comment]
output is "aarch64"

**Comment by cmacdonald** [comment]
I asked for 3 things...

**Comment by Nockda** [comment]
Probably you have an M1 Mac, and there is no compatible jnius library?
-- > Yes, I'm using M1 mac. I install jnius and pyjnius, but it didn't work.
Or your Python (x86_64) build mismatches your Java build (arm64)?
-- > I use pyhon 3.10 and java 11. I can't find how can I match this...

**Comment by cmacdonald** [comment]
Specifically
1. What is `platform.machine()` in Python?
2. What is `java -version` from the commandline?
3. What is `System.getProperty("os.arch")` from jshell?
4. What is `pip list -v | grep jnius` from the commandline?
5. What is `ls PATH/jnius` where PATH is the 3rd column in the output of 4 above?

**Comment by Nockda** [comment]
1. 'arm64'
2. 11.0.18
3. "aarch64"
4. jnius                         1.1.0       
pyjnius                       1.4.2       
5. /Users/**/miniforge3/lib/python3.10/site-packages/jnius
there is no column. 3rd file name is __pycache__

**Comment by cmacdonald** [comment]
Thanks. I was expecting (1) and (3) to differ somehow.

I'm looking to try to work out what platform Pyjnius was built for. My Intel iMac looks like this:
```shell
$ ls    /opt/anaconda3/lib/python3.8/site-packages/jnius/
__init__.py			__pycache__			env.py				jnius.cpython-38-darwin.so	reflect.py			signatures.py			src
$ file /opt/anaconda3/lib/python3.8/site-packages/jnius/jnius.cpython-38-darwin.so    
/opt/anaconda3/lib/python3.8/site-packages/jnius/jnius.cpython-38-darwin.so: Mach-O 64-bit bundle x86_64
```

I notice from `pip list` that you have both jnius (old) and pyjnius (newer) installed. Perhaps remove jnius and force reinstall of pyjnius?

However, the error message appears to be concerning Python loading Java, rather than Jnius.

I dont personally have a test environment for Mac M1. I'll try a colleagues machine later this week and report back.

See also https://github.com/kivy/pyjnius/issues/609

**Comment by cmacdonald** [comment]
Pyjnius 1.6.0 provided a version compiled for arm64 Macs. Does this solve your problem?

**Comment by cmacdonald** [comment]
No reply.
