### ISSUE TITLE
DPH calculation

### ISSUE THREAD

**Issue by ChrisGray0626** [terrier-org/terrier-core#219]
https://github.com/terrier-org/terrier-core/blob/30bad070d408b358b588c20aa671c0ee27fa3da2/modules/core/src/main/java/org/terrier/matching/models/DPH.java#L70-L80

Due to log function, when tf = 0,  the log function will cause Nan. I guess the correct result is 0 or tf shouldn't be 0?

**Comment by cmacdonald** [comment]
Best Matching models assume they are only called for terms that occur in the documents, as would be identified by the inverted index. So $tf > 0$ is the assumption. 

IIRC, DPH also assumes $tf < doclen$, i.e. a document cannot only contain one term - see discussion on page 12 of https://dl.acm.org/doi/10.1145/2037661.2037662 which I believe is also applicable to DPH.

**Comment by ChrisGray0626** [comment]
> Best Matching models assume they are only called for terms that occur in the documents, as would be identified by the inverted index. So tf>0 is the assumption.
> 
> IIRC, DPH also assumes tf<doclen, i.e. a document cannot only contain one term - see discussion on page 12 of https://dl.acm.org/doi/10.1145/2037661.2037662 which I believe is also applicable to DPH.

I know the term should occur in the document. But in our big data coursework, a query includes lots of query terms. There is no guarantee that every query term of this query occurs in this document. So when we try to get a mean score of pair of query and document, the term not in document should be skipped or just return zero? which will cause the different count and mean score.

**Comment by cmacdonald** [comment]
> big data coursework

Questions about the big data coursework should be referred to the course lecturer.

**Comment by ChrisGray0626** [comment]
I got it but I still want to know, according to the idea of this model, if I want to calculate the mean value of query term, the return value should be zero, infinity or skipped, Just theoretical.
Or this model need not consider this relationship. This is my final question, thank you.
