### ISSUE TITLE
Problems encountered when following the quick start guide

### ISSUE THREAD

**Issue by whenov** [terrier-org/terrier-core#7]
* The warning about SLF4J was raised. Since this is also a dependency of Terrier, maybe it should be mentioned;
* The `terrier.properties` file and `terrier.home` variable recursively depend on each other;
* An exception of `java.lang.IllegalStateException: No resultset found` was raised when calling the `SearchRequest.getResults()`. I solved the problem by copying the `terrier.properties.sample` file, but this should be mentioned in the guide;
* The code blocks in http://terrier.org/docs/v5.0/quickstart-integratedsearch.html and http://terrier.org/docs/v5.0/quickstart-integratedsearchdisk.html are broken.

Thanks!

**Comment by cmacdonald** [comment]
Thanks @whenov , we have addressed your suggestions for Terrier 5.1
