### ISSUE TITLE
Always require explicit specification of the file encoding used to process files in TREC format.

### ISSUE THREAD

**Issue by aboldin1** [terrier-org/terrier-core#87]
Right now, unless set by **trec.encoding** parameter, the file encoding is [implied](https://github.com/terrier-org/terrier-core/blob/5.x/doc/languages.md#file-encodings) from the default JVM encoding setting of a current machine. Such behaviour is ambiguous and affects cross-platform performance of the software package.

Recently, I've encountered an issue where batch indexing of an identical corpus in TREC format would result in different size of vocabulary on multiple Windows machines. Turns out the corpus likely contained a mixture of English and non-English text, and the machines had different encodings set as JVM default, therefore the corpus was not parsed in the same way.

Requirement to explicitly specify the file encoding will help to prevent such issues in future, let alone being a good practice in general. I would suggest either requiring user to configure the file encoding manually during the setup process, or adding **trec.encoding=utf-8** to the default **terrier.properties** file and prompting the user to alter the setting if needed. In both cases, the implicit choice of the file encoding based on JVM default encoding should be disabled.

**Comment by cmacdonald** [comment]
Thanks for your report. Can you tell us more about your collection, or show a sample document, so we can try to reproduce this? 

What was the language of the machines that it varied across - e.g. the `systeminfo` command.  Also the value of `java.nio.charset.Charset.defaultCharset()` when entered into the `jshell` command.

**Comment by aboldin1** [comment]
Thank you very much for your reply.

The system language of all machines was set to English (US). I've done some tests to check the JVM default encoding on all of them using `System.getProperty("file.encoding")`. One machine that has indexed the corpus correctly (identically to a Debian with default UTF-8) returned **CP-1252** as its default JVM encoding. Another, problematic one, has returned **GBK**.

Investigating further, I have discovered that on Windows, the JVM default encoding changes depending on system locale. When system locale of a "working" system is changed from English (United States) to Chinese (Simplified, China), its JVM default encoding changes to GBK and results in problems. You should be able to easily reproduce this behaviour yourself.

This behaviour seems counter-intuitive to me, as from my understanding, system locale setting is only intended for displaying legacy non-Unicode applications in Windows and should have nothing to do with JVM. I can therefore envision usage of JVM default encoding for parsing collections by default as a potential source of problem for users who have their system locale set to their home languages, even though their system language might be English.

I will also attach a sample from the collection I'm using a bit later, when I get access to it.

**Comment by cmacdonald** [comment]
Future versions of Terrier will force an trec.encoding=UTF-8 and will WARN if not set. Thanks for your feedback.
