### ISSUE TITLE
MRFDependenceScoreModifier

### ISSUE THREAD

**Issue by pluto-junzeng** [terrier-org/terrier-core#9]
terrier is a wonderful work

When I use the MRFDependenceScoreModifier model ,  but it has a question list this:

java.lang.ClassCastException: org.terrier.structures.postings.bit.BasicIterablePosting cannot be cast to org.terrier.structures.postings.BlockPosting

We try mang times  ,but  this question always  be

Thanks

**Comment by cmacdonald** [comment]
You need an index with positions.

**Comment by pluto-junzeng** [comment]
thanks

**Comment by cmacdonald** [comment]
For Terrier 5, `bin/terrier bi -b` is the shortest way

**Comment by pluto-junzeng** [comment]
Good way ！！
