### ISSUE TITLE
high_cpu_usage

### ISSUE THREAD

**Issue by stamatisvas** [terrier-org/terrier-core#98]
Terrier v5.2 is using very high cpu(i.e. using top in linux I found cpu between (100-200% and memory 10%)). Is there any way to controll it?

**Comment by cmacdonald** [comment]
during indexing or retrieval?

**Comment by stamatisvas** [comment]
During indexing

**Comment by cmacdonald** [comment]
I suspect it might be garbage collecting, but you dont show the logs, so we dont know where in indexing.

I would suggest upgrading to the Github current version, it should be faster.

**Comment by stamatisvas** [comment]
Upgrading to the github version solved the problem! Thanks!

**Comment by cmacdonald** [comment]
Good stuff, thanks. Version 5.3 wont be long.
